# # make use of vm's 
# sudo: 'required'
# language: ruby
# # building only for these branches
# branches:
#   only:
#   - master
# # have the docker service set up
# services:
#   - 'docker'
# # build and push the docker image for jenkins-lts-dind to docker hub
# before_install:
#   - docker build -t ramitmitra/jenkins-lts-dind .
#   - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERUSERNAME" --password-stdin
#   - docker push ramitmitra/jenkins-lts-dind

# make use of vm's 
sudo: 'required'

# have the docker service set up (we'll
# update it later)
services:
  - 'docker'
language: node_js
node_js:
  - "8"

# prepare the machine before any code
# installation scripts
before_install:
  - docker build -t ramitmitra/jenkins-lts-dind .
  - echo "$DOCKERPASSWORD" | docker login -u "$DOCKERUSERNAME" --password-stdin
  - docker push ramitmitra/jenkins-lts-dind

# first execute the test suite.
# after the test execution is done and didn't
# fail, build the images (if this step fails
# the whole Travis build is considered a failure).
# script:
#   - 'make test'
#   - 'make image'

# only execute the following instructions in
# the case of a success (failing at this point
# won't mark the build as a failure).
# To have `DOCKER_USERNAME` and `DOCKER_PASSWORD`
# filled you need to either use `travis`' cli 
# and then `travis set ..` or go to the travis
# page of your repository and then change the 
# environment in the settings pannel.
after_success:
  - if [[ "$TRAVIS_BRANCH" == "master" ]]; then
      docker login -u $DOCKERUSERNAME -p $DOCKERPASSWORD ;
      make push-image ;
    fi

# do notify me when things fail
notifications:
  email: false